app:
    region: us-east-1
    s3-bucket-prefix: "@no@-"
    max-width: 250
    max-height: 250
    thumbnail-bucket: "wildrydes-step-module-resources-thumbnails3bucket"

#spring5 + spring-cloud-aws 2 ...   
#cloud:
#    aws:
#        region:
#            static: us-west-2
#        credentials:
#            useDefaultAwsCredentialsChain: true