app:
    region: us-east-1
    thumbnail-bucket-base: "stylez-sls-handson-rekognition"
    thumbnail-bucket-prefix: "@no@-"
    thumbnail-bucket-suffix: "-thumbnails"
    max-width: 250
    max-height: 250

#spring5 + spring-cloud-aws 2 ...   
#cloud:
#    aws:
#        region:
#            static: us-west-2
#        credentials:
#            useDefaultAwsCredentialsChain: true